### ISSUE TITLE
home / root / catalog confusion

### ISSUE THREAD

**Issue by zwilias** [backstage/demo#528] opened 2024-07-28 10:48 UTC
Currently, the demo-site is set up to:

- reroute `/` to `/catalog`
- have the homepage on `/home`

When directing my browser to https://demo.backstage.io, I somewhat expected to land on the homepage. It may very well be a conscious choice not to do so, but I do want to call out that it seems somewhat expected, especially given it's the very first navigation item.

What happens instead is that I'm redirected to the catalog on `/catalog` (also fine!) but no navigation items are active. I imagine this is simply because https://github.com/backstage/demo/blame/1fcb20399e8ddfa5d697029d538eda236a12295f/packages/app/src/components/Root/Root.tsx#L87 we link to `/` in the sidebar nav.

I think that should be changed to link to `/catalog`, if only to make the nav highlight correctly.

Further, I'd also argue that the homepage plugin can/should be mounted on `/` instead of `/home`. That is a bit more opinionated, but it also doesn't seem "weird" to have the homepage be the entry point.

I can follow up with 2 PR's:

1. link to `/catalog` in the sidebar "Catalog" item to get the nav highlighting correctly. This should be rather uncontroversial.
2. serve the homepage on `/` instead of `/home`. Since it's a bit more of an opinionated take, having it be a separate PR makes it easier to have focused discussion, without blocking the fix for the nav.

Does that sounds alright to y'all?

**Comment by awanlin** [comment] 2024-07-31 12:33
Hi @zwilias, this is by design. One of the things we try to balance with this Demo site is what the experience will be like when potential Adopters create their first Backstage instance. We want it to mimc that and currently Catalog is where you land and there is no Home. This compromise allows us to show other features like the Home Page. I did also note that in the PR - https://github.com/backstage/demo/pull/186 - when I added the Home plugin.

Hope that helps?

**Comment by zwilias** [comment] 2024-07-31 13:15
Gotcha, that makes sense. How would you feel about pointing the catalog sidebar item to `/catalog`?

That would retain everything the way it is now (given `/` navigates to the catalog) but allow the item to be highlighted.

**Comment by awanlin** [comment] 2024-08-01 12:36
Sure, if you feel like it really needs to change, feel free to submit a PR for that 👍

**Comment by awanlin** [comment] 2024-08-29 19:55
Going to close this, if you want to follow up with a PR feel free.

**Closed by awanlin** 2024-08-29 19:55 UTC
